### ISSUE TITLE
TLS-Crypt option is not backwards compatible

### ISSUE THREAD

**Issue by widders** [lisenet/docker-openvpn#20]
First, thanks for updating the kylemann image.

We noticed when issuing new certificates they are no longer compatible with the old server due to the `<tls-auth>/<tls-crypt>` change. Reading around this it looks like server won't be compatible with `<tls-auth>` certificates if we change it to `<tls-crypt>`

From what I've read so far it would probably be best to move to `tls-cryptv2` in general as it seems it should support both but maybe this should be configurable.

Also because you've built to the same image tag in docker hub the change just got silently applied in some places and not others, maybe it would be better to build to a new release tag?

**Comment by lisenet** [comment]
Thanks for letting me know. I'll do some reading on `tls-cryptv2`.

The change was applied to build [2.6.6-build20](https://github.com/lisenet/docker-openvpn/releases/tag/2.6.6-build20). The previous build [2.6.6-build19](https://github.com/lisenet/docker-openvpn/releases/tag/2.6.6-build19) should still use `<tls-auth>`. The `latest` tag is indeed a rolling release and will be updated every time there is a new build (this is by design). There is a bit more info on the release process [here](https://github.com/lisenet/docker-openvpn#release-process).
